// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("webapi.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<int?>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "hamada",
                            Color = "Blue",
                            Gender = "Men",
                            Price = 30.0,
                            Size = 10
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "My brand",
                            Color = "Black",
                            Gender = "Men",
                            Price = 35.0,
                            Size = 12
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "your brand",
                            Color = "Pink",
                            Gender = "Women",
                            Price = 28.0,
                            Size = 8
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "your brand",
                            Color = "yello",
                            Gender = "Women",
                            Price = 30.0,
                            Size = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
