// <auto-generated/>
#pragma warning disable 1591
namespace AspNetCoreGeneratedDocument
{
#line default
    using TModel = global::System.Object;
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "/Users/mohamadelhajhassan/code/work/dotnet-projects/WebApp/Views/_ViewImports.cshtml"
    using WebApp;

#nullable disable
#nullable restore
#line 2 "/Users/mohamadelhajhassan/code/work/dotnet-projects/WebApp/Views/_ViewImports.cshtml"
    using WebApp.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/Users/mohamadelhajhassan/code/work/dotnet-projects/WebApp/Views/Shirts/CreateShirt.cshtml")]
    [global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
#nullable restore
    internal sealed class Users_mohamadelhajhassan_code_work_dotnet_projects_WebApp_Views_Shirts_CreateShirt : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Shirt>
#nullable disable
    {
#pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__()
        {
            ((global::System.Action)(() =>
            {
#nullable restore
#line 1 "/Users/mohamadelhajhassan/code/work/dotnet-projects/WebApp/Views/Shirts/CreateShirt.cshtml"
                Shirt __typeHelper = default!;

#line default
#line hidden
#nullable disable
            }
            ))();
        }
#pragma warning restore 219
#pragma warning disable 0414
        private static object __o = null;
#pragma warning restore 0414
#pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
#pragma warning restore 1998
#nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
#nullable disable
#nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
#nullable disable
#nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
#nullable disable
#nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
#nullable disable
#nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Shirt> Html { get; private set; } = default!;
#nullable disable
    }
}
#pragma warning restore 1591
